export { default as Main } from "./Main";
export { default as Navbar } from "./Navbar";
export { default as Profile } from "./Profile";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Locations } from "./Locations";
export { default as Cart } from "./Cart";
